[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2 ; passt auch fuer LoLin NodeMCU V3
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    bblanchon/ArduinoJson@^7.4.1
    adafruit/RTClib@^2.1.4
